import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5173/paint');
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.waitForFunction(() => window.__cube?.ready === true, null, { timeout: 30000 });
await page.evaluate(() => window.__cube.setOrientation({ top: 'U', front: 'F', yaw: 0, pitch: 0 }, false));
await page.waitForTimeout(150);
await page.keyboard.press('3');
const pts = await page.evaluate(() => [0,1,2,3,5,6,7,8].map(k => { const i = 18+k; const c = window.__cube; const canvas = document.querySelector('.cube3d canvas'); const r = canvas.getBoundingClientRect(); const p = c.stickers[i].position.clone(); p.applyQuaternion(c.qDrift.clone().multiply(c.qOrientation)); p.y += c.floatY; p.project(c.camera); return { x: r.left + (p.x+1)/2*r.width, y: r.top + (1-p.y)/2*r.height }; }));
for (const p of pts) await page.mouse.click(p.x, p.y);
await page.waitForTimeout(300);
console.log(await page.evaluate(() => window.__cube.displayFacelets.slice(18, 27)));
console.log((await page.evaluate(() => window.__gest)).join('\n'));
await browser.close();
