import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://localhost:5173/');
await page.evaluate(() => localStorage.setItem('cube.session.v1', JSON.stringify({ state: { facelets: 'UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB', paintHistory: [], lastInput: 'paint', learn: null, solved: { ms: 252000, moves: 84, at: Date.now() }, settings: { sound: false, voice: false, seenPaintHint: true, seenLearnHint: false } }, version: 1 })));
await page.goto('http://localhost:5173/solved');
await page.waitForFunction(() => window.__cube?.ready === true, null, { timeout: 30000 });
await page.waitForTimeout(3000);
console.log(await page.evaluate(() => { const box = (sel) => { const e = document.querySelector(sel); if (!e) return null; const r = e.getBoundingClientRect(); return [Math.round(r.top), Math.round(r.height)]; }; return { screen: box('.screen'), stage: box('.stage'), canvas: box('canvas'), copy: box('.solved-copy'), actions: box('.solved-actions'), docH: document.documentElement.scrollHeight, actionsOpacity: getComputedStyle(document.querySelector('.solved-actions') || document.body).opacity }; }));
await browser.close();
